INSERT INTO "Reminders" VALUES (1,1,'Ben''s Birthday Party','2019-01-20 11:30:00');
INSERT INTO "Reminders" VALUES (2,0,'Go to Market','2019-08-17 15:00:00');
INSERT INTO "Reminders" VALUES (3,1,'Hello World!',strftime('%Y-%m-%d %H:00:00','now','+1 hour'));
INSERT INTO "Reminders" VALUES (4,1,'Anniversary','2019-11-16 08:00:00');
INSERT INTO "Reminders" VALUES (5,1,'Christmas Party','2019-12-25 13:30:00');
INSERT INTO "Notes" VALUES (1,'Note 1','Lorem ipsum dolor sit amet consectetur adipiscing elit, mattis vestibulum dis dictum primis tempor, varius nisl ornare nisi conubia litora. Aptent phasellus molestie habitant eu aliquet luctus conubia placerat, sapien lectus cursus eget condimentum euismod volutpat curae pellentesque, fringilla turpis class ultricies vivamus nam cras.','2017-02-11 06:33:45');
INSERT INTO "Notes" VALUES (2,'Note 2','Lorem ipsum dolor sit amet consectetur adipiscing elit, mattis vestibulum dis dictum primis tempor, varius nisl ornare nisi conubia litora. Aptent phasellus molestie habitant eu aliquet luctus conubia placerat, sapien lectus cursus eget condimentum euismod volutpat curae pellentesque, fringilla turpis class ultricies vivamus nam cras.','2017-07-04 08:03:11');
INSERT INTO "Notes" VALUES (3,'Note 3','Lorem ipsum dolor sit amet consectetur adipiscing elit, mattis vestibulum dis dictum primis tempor, varius nisl ornare nisi conubia litora. Aptent phasellus molestie habitant eu aliquet luctus conubia placerat, sapien lectus cursus eget condimentum euismod volutpat curae pellentesque, fringilla turpis class ultricies vivamus nam cras.','2018-06-05 11:33:36');
INSERT INTO "Notes" VALUES (4,'Note 4','Lorem ipsum dolor sit amet consectetur adipiscing elit, mattis vestibulum dis dictum primis tempor, varius nisl ornare nisi conubia litora. Aptent phasellus molestie habitant eu aliquet luctus conubia placerat, sapien lectus cursus eget condimentum euismod volutpat curae pellentesque, fringilla turpis class ultricies vivamus nam cras.','2018-11-21 13:00:00');
INSERT INTO "Notes" VALUES (5,'Note 5','Lorem ipsum dolor sit amet consectetur adipiscing elit, mattis vestibulum dis dictum primis tempor, varius nisl ornare nisi conubia litora. Aptent phasellus molestie habitant eu aliquet luctus conubia placerat, sapien lectus cursus eget condimentum euismod volutpat curae pellentesque, fringilla turpis class ultricies vivamus nam cras.','2018-12-12 06:00:28');
INSERT INTO "Notes" VALUES (6,'Note 6','Lorem ipsum dolor sit amet consectetur adipiscing elit, mattis vestibulum dis dictum primis tempor, varius nisl ornare nisi conubia litora. Aptent phasellus molestie habitant eu aliquet luctus conubia placerat, sapien lectus cursus eget condimentum euismod volutpat curae pellentesque, fringilla turpis class ultricies vivamus nam cras.','2019-01-01 00:00:00');
INSERT INTO "Notes" VALUES (7,'Note 7','Lorem ipsum dolor sit amet consectetur adipiscing elit, mattis vestibulum dis dictum primis tempor, varius nisl ornare nisi conubia litora. Aptent phasellus molestie habitant eu aliquet luctus conubia placerat, sapien lectus cursus eget condimentum euismod volutpat curae pellentesque, fringilla turpis class ultricies vivamus nam cras.','2019-02-14 08:40:17');
INSERT INTO "Notes" VALUES (8,'Note 8','Lorem ipsum dolor sit amet consectetur adipiscing elit, mattis vestibulum dis dictum primis tempor, varius nisl ornare nisi conubia litora. Aptent phasellus molestie habitant eu aliquet luctus conubia placerat, sapien lectus cursus eget condimentum euismod volutpat curae pellentesque, fringilla turpis class ultricies vivamus nam cras.','2019-03-06 09:15:56');
INSERT INTO "Notes" VALUES (9,'The quick brown fox','The quick brown fox jumps over the lazy dog.','2019-08-15 09:46:33');
INSERT INTO "Notes" VALUES (10,'Greetings!','Hello World!
Comment ça va?',strftime('%Y-%m-%d %H:00:00','now'));